general {
    immediate_render = true
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/Pictures/lock-screen.png
    blur_passes = 4
    blur_size = 7
    brightness = 0.24
    contrast = 1.04
    saturation = 0.72
}

label {
    monitor =
    text = cmd[update:0] printf ' ░▒▓██████▓▒░ ░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░ ░▒▓███████▓▒░ \n░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░        \n░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░        \n░▒▓█▓▒░      ░▒▓████████▓▒░▒▓█▓▒░      ░▒▓████████▓▒░░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░  \n░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░ \n░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░   ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░ \n ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒░    ░▒▓██████▓▒░░▒▓███████▓▒░  '
    color = rgba(137, 180, 250, 0.98)
    font_size = 11
    font_family = CaskaydiaCove Nerd Font Mono
    position = 0, 115
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] printf '%s' "$(date +'%H:%M:%S')"
    color = rgba(205, 214, 244, 0.98)
    font_size = 28
    font_family = CaskaydiaCove Nerd Font Mono
    position = 0, -75
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] printf '%s' "$(date +'%A, %d %B %Y')"
    color = rgba(166, 173, 200, 0.92)
    font_size = 14
    font_family = CaskaydiaCove Nerd Font Mono
    position = 0, -116
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:0] printf 'username: %s' "$(whoami)"
    color = rgba(166, 227, 161, 0.96)
    font_size = 16
    font_family = CaskaydiaCove Nerd Font Mono
    position = -112, -156
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:0] printf 'password: '
    color = rgba(166, 227, 161, 0.96)
    font_size = 16
    font_family = CaskaydiaCove Nerd Font Mono
    position = -150, -198
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(205, 214, 244, 0.96)
    font_family = CaskaydiaCove Nerd Font Mono
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    dots_center = false
    dots_text_format = *
    dots_size = 0.40
    dots_spacing = 0.18
    check_color = rgba(166, 227, 161, 0.96)
    fail_color = rgba(243, 139, 168, 0.96)
    fail_text = wrong password
    fail_transition = 200
    rounding = 0
    capslock_color = rgba(250, 179, 135, 0.92)
    position = 85, -198
    halign = center
    valign = center
}
